import chicken from "@/assets/images/chicken.jpeg";
import coldstone from "@/assets/images/coldstone.jpeg";

let stores = [
    {
      name: "Chicken Republic",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:false,
      id:1,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: chicken,
      discount: {
        amount: 0,
        percent: 20,
        code: "BADJD",
      },
      rating: {
        rate: 4.3,
        number: 200,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "25 Min",
    },
    {
      name: "Cold Stone",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:false,
      id:2,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: coldstone,
      discount: null,
      rating: {
        rate: 3.2,
        number: 168,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "30 Min",
    },
    {
      name: "Chicken Republic",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:false,
      id:3,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: chicken,
      discount: {
        amount: 0,
        percent: 20,
        code: "BADJD",
      },
      rating: {
        rate: 4.3,
        number: 200,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "25 Min",
    },
    {
      name: "Cold Stone",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:false,
      id:4,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: coldstone,
      discount: null,
      rating: {
        rate: 3.2,
        number: 168,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "30 Min",
    },
    {
      name: "Chicken Republic",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:true,
      id:5,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: chicken,
      discount: {
        amount: 0,
        percent: 20,
        code: "BADJD",
      },
      rating: {
        rate: 4.3,
        number: 200,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "25 Min",
    },
    {
      name: "Cold Stone",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:true,
      id:6,
      storeClosed: false,
      workingHours: {
        opening: 8,
        closing: 20,
      },
      favourite: false,
      cover: coldstone,
      discount: null,
      rating: {
        rate: 3.2,
        number: 168,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "30 Min",
    },
    {
      name: "Chicken Republic",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:true,
      id:7,
      storeClosed: false,
      workingHours: {
        opening: 7,
        closing: 18,
      },
      favourite: false,
      cover: chicken,
      discount: {
        amount: 0,
        percent: 20,
        code: "BADJD",
      },
      rating: {
        rate: 4.3,
        number: 200,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "25 Min",
    },
    {
      name: "Cold Stone",
      contact: {
        state: "Bayelsa",
        address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
        phoneNumber: "09088978929",
        email: "info@chicken-republic.com",
        website: "https://chicken-republic.com",
      },
      featured:true,
      id:8,
      storeClosed: false,
      workingHours: {
        opening: 7,
        closing: 18,
      },
      favourite: false,
      cover: coldstone,
      discount: null,
      rating: {
        rate: 3.2,
        number: 168,
      },
      delivery: {
        free: false,
        price: 400,
      },
      averageDeliveryTime: "30 Min",
    },
    {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:9,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:10,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:11,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:12,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:13,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:14,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:15,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:16,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:17,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:18,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:19,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:20,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:21,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:22,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:23,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:24,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:25,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:26,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
      {
        name: "Chicken Republic",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:27,
        storeClosed: false,
        workingHours: {
          opening: 7,
          closing: 18,
        },
        favourite: false,
        cover: chicken,
        discount: {
          amount: 0,
          percent: 20,
          code: "BADJD",
        },
        rating: {
          rate: 4.3,
          number: 200,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "25 Min",
      },
      {
        name: "Cold Stone",
        contact: {
          state: "Bayelsa",
          address: "Kpansia, Beside God is Good Motors, Mbiama – Yenagoa Road",
          phoneNumber: "09088978929",
          email: "info@chicken-republic.com",
          website: "https://chicken-republic.com",
        },
        featured:false,
        id:28,
        storeClosed: false,
        workingHours: {
          opening: 8,
          closing: 20,
        },
        favourite: false,
        cover: coldstone,
        discount: null,
        rating: {
          rate: 3.2,
          number: 168,
        },
        delivery: {
          free: false,
          price: 400,
        },
        averageDeliveryTime: "30 Min",
      },
  ]

  export default stores;